### ISSUE TITLE
GUI Support for Network ACL

### ISSUE THREAD

**Issue by nikhilreddie** [lxdware/lxd-dashboard#10]
Can we have a form type of Network ACL creation and defining it too rather than setting Network ACL's by typing JSON.

**Comment by matthewalanpenning** [comment]
That is a very good suggestion, thanks!  I have coded in a GUI option for configuring Egress and Ingress rules for Network ACLs. I am going through a testing process for itand expect to have it pushed out in version 2.1.0 within a few weeks.

**Comment by matthewalanpenning** [comment]
I just pushed out v2.1.0 and it now has support for adding Egress and Ingress rules in Network ACLs.
