### ISSUE TITLE
Network ACL rules

### ISSUE THREAD

**Issue by Prabhat798** [lxdware/lxd-dashboard#11]
Unable to create Network ACL rules using Web UI. Had to write a json file for that. But not able to get any sample json for the same.

**Comment by matthewalanpenning** [comment]
I will have a GUI option for writing Egress and Ingress rules coming in version 2.1.0 within a few weeks to make it easier.

**Comment by matthewalanpenning** [comment]
If you are still looking for sample JSON code, look here: https://linuxcontainers.org/lxd/api/master/#/network-acls/network_acls_post
