### ISSUE TITLE
Not adding existing containers to the lxd-dashboard 

### ISSUE THREAD

**Issue by elbrinke** [lxdware/lxd-dashboard#12]
Hi 

I set up the lxd-dashboard and connected it to some of our lxd servers. It connects successfully but is not able to pick up existing containers. 

It keeps on showing: "**Executing su command on 'container**'. 

Can you please assist me with getting this sorted? 
LXD version = 3.0.3

Regards
Eddy

**Comment by matthewalanpenning** [comment]
Hello Eddy. The dashboard uses the /1.0/instances endpoint which was not available in version 3.0.3. This version uses /1.0/containers as the endpoint. It may be as simple as changing all of the endpoints in the https://github.com/lxdware/lxd-dashboard/blob/master/lxd-dashboard/php/lxd/instances.php file to get it working. As far as the "Executing su command" there is most likely an exec operating running on one of your containers.

**Comment by matthewalanpenning** [comment]
I am working now on the next major release (v3) of the dashboard. There are several advantages on separating out instances into two different pages on the dashboard, containers and virtual-machines. This would allow for backwards compatibility with older versions like 3.0.3. I have an Ubuntu 18.04 setup with LXD 3.0.3 for testing. If you are familiar with PHP coding I did get the latest 2.4.0 version of the dashboard working with LXD 3.0.3 by making a few tweaks. I can share the tweaks if interested. I expect to have the next major release of the dashboard out sometime this Fall.

**Comment by matthewalanpenning** [comment]
This should now be resolved. Tested on LXD 3.0.3 Ubuntu 18.04. Virtual machines are unsupported, but containers are supported for this version.
