### ISSUE TITLE
Invalid config: Unknown configuration key: limits.cpu.allowance

### ISSUE THREAD

**Issue by kevinwells22** [lxdware/lxd-dashboard#13]
I am running latest LXD-Dashboard, and LXD 4.18. I have a VM, but when I try and update the CPU I get this error:

`Invalid config: Unknown configuration key: limits.cpu.allowance`

Same with Ram update, I get:

`Invalid config: Unknown configuration key: limits.memory.enforce`

**Comment by matthewalanpenning** [comment]
Hello @speedyrazor. Some of the instance configuration keys are specific to containers and other to virtual machines. Both _limits.cpu.allowance_ and _limits.memory.enforce_ can only be applied to container type instances. Here is a reference link: [https://linuxcontainers.org/lxd/docs/master/instances](https://linuxcontainers.org/lxd/docs/master/instances).  I will add to the form hints indicating which configuration settings are specific to an instance type in the next update.

**Comment by speedyrazor** [comment]
Hi, thnks for your reply. Is there anyway to use the CPU Limits and Memeory Limits within the GUI for VM's please, perhaps if VM, grey out that setting, or ignore it?
As this is the most comprehensive open source LXD manager I have found, and it looks and feels great. I come from a KVM / Virt-Manager background, so I am looking for a replacement but for LXD.

**Comment by matthewalanpenning** [comment]
Yes, that is a good idea to disable the fields for virtual-machine or container only options where applicable on the GUI and allow for processing of only those items . I will plan on doing that in the next update which should roll out within the week.

**Comment by speedyrazor** [comment]
Hi, that is great new, thank you. I am more than happy to help in nayway I can, testing, etc.
Please let me know.
Kind regards.

**Comment by matthewalanpenning** [comment]
Version 2.3.0 has just been released and this should now fix the issues you were having with CPU Limits and Memory Limits. Let me know if you have any more issues.

**Comment by kevinwells22** [comment]
This is great, thanks. I've just installed this new version, I'll report back any issues.
I have lots of other suggestions of things to implent whihc I do regually, if you're interested?
