### ISSUE TITLE
Docker Upgrade Procedure

### ISSUE THREAD

**Issue by gaia** [lxdware/lxd-dashboard#14]
New user here, this is by far the best LXC manager GUI out there. Thank you Matthew!

How do I upgrade a docker install (from previous version to current)?

**Comment by matthewalanpenning** [comment]
Gaia, thank you so much!
I am going to assume you used the command **_docker run -d --name dashboard -p 80:80 -v ~/lxdware:/var/lxdware --restart=always lxdware/dashboard:latest_** to create your docker image. There are three basic steps to upgrade the Docker image. 
1. First download the new version to your computer. You can use the command: **_docker pull lxdware/dashboard:latest_**
2. You will need to delete the current container that you have running. You can use the command: **_docker rm -f lxd-dashboard_**
3. Create and run the new container based on the updated image. This is the same command as you ran the first time: **_docker run -d --name dashboard -p 80:80 -v ~/lxdware:/var/lxdware --restart=always lxdware/dashboard:latest_**

**Comment by gaia** [comment]
great, thx matthew. don't forget `docker system prune -a --volumes` to remove dangling leftovers!
