### ISSUE TITLE
Docs for 2.x install only

### ISSUE THREAD

**Issue by cvmiller** [lxdware/lxd-dashboard#23]
Trying to install 3.1.0, however only find the Doc for installing 2.x

https://lxdware.com/installing-the-lxd-dashboard-in-an-lxc-container-v2-x-x/

I have followed this, however running into other issues (see another issue)

**Comment by matthewalanpenning** [comment]
Craig,
The installation instructions are the same for both 3.x and 2.x versions. I will work to get that updated in on the webpage.
Thanks,
Matt

**Comment by cvmiller** [comment]
Thanks, I am collecting notes for installing on Alpine Linux, which is a much smaller container than Ubuntu. I'll pass these back, once I get things running, and perhaps that can be added to the Doc.
