### ISSUE TITLE
Container List displays 'Root Disk' of 0 MB for all containers 

### ISSUE THREAD

**Issue by cvmiller** [lxdware/lxd-dashboard#26]
Running lxd-dashboard v3.10.

I have multiple hosts running LXD. On some hosts(paikea), the root disk displays the space each container has for persistent storage. On others (koa) it does not. See attached screen shots.

Additional host LXD version information,
* paikea v4.21
* koa v4.20
*
![paikea_container_list](https://user-images.githubusercontent.com/351123/148257095-4ca60193-a1bf-49bf-adf4-358a778184c3.png)
![koa_container_list](https://user-images.githubusercontent.com/351123/148257113-19537129-4124-4350-94ca-6ffee74568a0.png)

**Comment by cvmiller** [comment]
Some additional information. For some reason, `lxc info <container>` doesn't show the disk usage on koa (bottom screen):

```
$ lxc info lxdware
Name: lxdware
Status: RUNNING
Type: container
Architecture: x86_64
PID: 27708
Created: 2022/01/02 15:20 PST
Last Used: 2022/01/02 15:20 PST

Resources:
  Processes: 17
  CPU usage:
    CPU usage (in seconds): 235
  Memory usage:
    Memory (current): 125.77MiB
    Memory (peak): 135.39MiB
  Network usage:
    lo:
      Type: loopback
      State: UP
      MTU: 65536
      Bytes received: 121.12MB
      Bytes sent: 121.12MB
      Packets received: 392899
      Packets sent: 392899
      IP addresses:
        inet:  127.0.0.1/8 (local)
        inet6: ::1/128 (local)
    eth0:
      Type: broadcast
      State: UP
      Host interface: vethf52b5629
      MAC address: 00:16:3e:84:8e:3e
      MTU: 1500
      Bytes received: 231.40MB
      Bytes sent: 122.00MB
      Packets received: 506643
      Packets sent: 424860
      IP addresses:
        inet:  10.1.1.104/24 (global)
        inet6: 2607:c000:8011:fd00:216:3eff:fe84:8e3e/64 (global)
        inet6: fe80::216:3eff:fe84:8e3e/64 (link)
```
Not sure why. But I am guessing this is where you are getting this information. **Perhaps N/A would be better than 0** in that column.

**Comment by matthewalanpenning** [comment]
That is interesting. I have not encountered this before. I do pull that value from the LXD info. I can certainly replace a null value with N/A.

**Comment by cvmiller** [comment]
I have 4 hosts running containers, which makes LXD Dashboard so useful. The hosts are x86_64, arch64, and arm7l (a Pi). 3 of the hosts are running a version of 4.x, The last is running 3.x. They all report info a little differently. In the screen captures (above) top is a arm7l, the bottom is x86_64.

Thanks for considering N/A when the return values are null.

**Comment by matthewalanpenning** [comment]
Can you verify that the latest version now fixes the issue with the disk value of 0MB? It should be replaced with an NA. I don't have an testing machines listing a disk value at 0.  Thanks.

**Comment by matthewalanpenning** [comment]
Thanks. No hurry. I am pretty sure it has been corrected. Yes, you will have to just go through a re-install.

**Comment by cvmiller** [comment]
Sorry this took so long. Just installed v3.4, and rood disk shows as N/A rather than 0. Thanks for the fix.
