### ISSUE TITLE
Feature Request: Delete <object> ask for confirmation

### ISSUE THREAD

**Issue by cvmiller** [lxdware/lxd-dashboard#27]
Using v3.10. While troubleshooting why the host overview data wasn't being displayed. I deleted the host by clicking on the 'trash' icon. It disappeared immediately! 

I expected some form of "are you sure you want to delete this host?" confirmation. A confirmation dialog would prevent accidental deletions.

**Comment by matthewalanpenning** [comment]
That is a good idea. I will work to add that in the next release.

**Comment by cvmiller** [comment]
Great, I look forward to it.

**Comment by matthewalanpenning** [comment]
There is now a confirmation before deleting hosts as version 3.2.0. Thanks for the great idea.
