### ISSUE TITLE
Support the project

### ISSUE THREAD

**Issue by Awoolyx** [lxdware/lxd-dashboard#32]
Hello there,

Any way to support this project (money wise)?

All the best

**Comment by matthewalanpenning** [comment]
Awoolyx,
Thanks for the question. I just created a [Ko-fi ](https://ko-fi.com/lxdware) page as well as a [Paypal](https://www.paypal.com/donate/?hosted_button_id=V43GWYPJDTTES) option and linked them through a [donate](https://lxdware.com/donate/) page that I created on the main site. I appreciate you asking.
Matt

**Comment by Awoolyx** [comment]
That's so lovely of you, thank you so much!
