### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by markc** [lxdware/lxd-dashboard#34]
Is the codebase ready for PHP 8.1 in Ubuntu 22.04?

**Comment by matthewalanpenning** [comment]
Great question markc. There are some issues when testing in PHP 8 of other distros. I will be pushing out a new release (3.2) this weekend and then after that will start working to make it ready for the upcoming LTS Ubuntu.

**Comment by matthewalanpenning** [comment]
There were a few changes that needed to be made to get the LXD dashboard working with PHP 8. Notably the default error handling of PDO exceptions changed. I also had to create a function for recursive in_array searches from the PDO fetchall function when checking if a field column exists. I added a setup of install instructions on the web site https://lxdware.com/installing-the-lxd-dashboard-on-ubuntu-22-04/

**Comment by markc** [comment]
Well done. I followed your instructions on a Manjaro/KDE desktop with snap lxd version 4.24, and it worked! The only small comment I would make in the instructions is that wget and nano need to be installed along the way. I'd also drop the $ in the code sections, so the instructions could be more easily copied n pasted. Or maybe add a combined code section, almost like a standalone script, that could be copied n pasted in one go.

**Comment by matthewalanpenning** [comment]
Very good. I dropped the $ on the install guide and also added wget to the set of install packages. Thanks for the suggestions.
