### ISSUE TITLE
Scheduled Backup / Snapshot

### ISSUE THREAD

**Issue by jcbeppler** [lxdware/lxd-dashboard#4]
Hello, congratulations for the very nice project!

One thing which just came to my mind, is having maybe a separate tab where you could configure a scheduled Snapshot/Backup.

What do you think?

**Comment by matthewalanpenning** [comment]
@jcbeppler thanks for the suggestion. I think that could definitely be an option in near future releases using PHP to set a cron job. The only hiccup that I can see is that if a user powers off the LXD dashboard, it would not send API requests to create snapshots/backups on the regular schedule.

**Comment by jcbeppler** [comment]
Hi @matthewalanpenning , true regarding the power off but the idea of the dashboard is that a user can monitor everything without having to go into the shell... so I imagine that the user won't stop and start the container every time he/she needs to use it... but I may be wrong.

**Comment by matthewalanpenning** [comment]
I think I have a good working solution for this that I have been testing. The basic idea is to have cron check a cron.php file every minute on the system. The cron.php file will query the database to see what backups or snapshots have been scheduled by the user. If the scheduled time matches, the snapshot or backup request is then sent to the host.

I am currently working on version 2.0.0 which introduces a more advanced framework for supporting multiple users and roles. I will plan to introduce this new feature in that release.

**Comment by matthewalanpenning** [comment]
Version 2.0.0 is now released. LXD allows for scheduling snapshots on a cron based schedule, including the naming convention and expiration. This is now supported in the dashboard and can be configured on the instance page. Unfortunately backups are not yet part of the LXD REST API. If that becomes an option, I will add that capability as well.
