### ISSUE TITLE
[contact] Seek contact with Matthew

### ISSUE THREAD

**Issue by erik78se** [lxdware/lxd-dashboard#48]
I'm trying to connect with Mathew Penning @matthewalanpenning (owner of the repo). I've tried to get in contact with him/you for some time to no avail.

I hope you are all well if you read this and please connect with me if you see this message.

/E

**Comment by matthewalanpenning** [comment]
Thanks for reaching out Erik, I found your emails and am replying back to them. Apologies for missing them.
