### ISSUE TITLE
Close websockets on exit from exec

### ISSUE THREAD

**Issue by danieldean** [lxdware/lxd-dashboard#58]
Hi,

I have been using your project for a while and been through a few upgrades all of which have gone smoothly. There is a modification I apply each time I update which closes the websockets  when the `exit` command is given in a terminal. Without this the websockets remain open and I need to remember to click `Stop Exec`.

I know you have a `beforeunload` event that should prevent websockets from getting left open but I have occasionally found this has not worked and ends up requiring a restart of LXD or the server to end the operation. I think this issue mostly occurs with mobile use but I think it may have happened a few times on desktop too.

I would have thought this issue is only applicable to exec as `exit` on a console should instead return to login.

Would you be able to incorporate this or accept it as a pull request?

https://github.com/danieldean/lxd-dashboard/commit/dfffdb7efea4dd37dcd9d23441681ff33bbe72b5

So far as I can tell no other issues arrise from including this (I have been using/testing it for a couple of years).

Thanks

Daniel

**Comment by matthewalanpenning** [comment]
Hello Daniel,

Yes I would like to incorporate your change. Could you provide a pull request? I am going to put a new release out in the first week of January and I will try to get this merged in before the next release.

Thanks,
Matt

**Comment by matthewalanpenning** [comment]
Thanks! I your code is now merged in.

**Comment by danieldean** [comment]
Thanks. Look forward to the new release.
