### ISSUE TITLE
Update Notifier (Footer)

### ISSUE THREAD

**Issue by radumamy** [lxdware/lxd-dashboard#6]
Hi Matthew,

Could we please have an update notifier built into the dashboard (similar to pi-hole)?

Many thanks.

Kind Regards,
Radu

**Comment by matthewalanpenning** [comment]
Radu,
Yes, this is something that I plan to implement in an upcoming release. Great suggestion.

**Comment by matthewalanpenning** [comment]
I just released version v2.1.0 and in the About modal there is a button that a user can click to check for newer versions.

**Comment by radumamy** [comment]
Thank you Matthew for implementing this. Apologies, I didn't had a chance to look at it. I'm sure it will be great.
