### ISSUE TITLE
Attaching/Detaching Volume to Instance

### ISSUE THREAD

**Issue by nikhilreddie** [lxdware/lxd-dashboard#9]
Please add a feature to attach/detach a volume to instance. We already have a feature to create a volume from storage pool but attaching/detaching created volume to instance is missing which is there in LXD-MOSAIC.

**Comment by matthewalanpenning** [comment]
Thanks, another great suggestion. I have coded a GUI option for attaching/detaching disk devices, proxy devices, and network devices that I am planning on including in the 2.1.0 version that should be released in a few weeks.

**Comment by nikhilreddie** [comment]
@matthewalanpenning Is it possible to add those devices to instance when it is running?

**Comment by matthewalanpenning** [comment]
Yes and no. Yes I can add storage volumes while a container instance is running and it mounts into the system just fine. For virtual machine instances the LXD REST API responds back stating that the instance must be turned off before adding a storage volume.

**Comment by matthewalanpenning** [comment]
I just pushed out v2.1.0 and it now has support for adding disk devices to instances using a web form.
